### PR TITLE
Bug: Fix geocoding sample

### PR DESCRIPTION
**Pull request by mmgaw113**
**Sample**

Geocoding Sample

**Checklist**

- [x] PR title follows convention - `keyword: Short description of change` 
- [x] PR targets the correct branch 
- [x] New Blueprints follow Unreal Naming Convention 
- [x] Self-review of changes
- [x] There are no warnings related to changes
- [x] A build was made and tested on all relevant platforms
- [x] No unrelated changes have been made to any other code or project files
- [x] No unnecessary includes or namespaces added
- [x] Code follows plugin coding style
- [x] New code and changed code has proper formatting 
- [x] No unintentional formatting changes
- [x] Commits have descriptive titles

**Blueprints**
N/A

**ArcGIS Maps SDK Version**

Maps SDK 1.7 w/ UE 5.3

### CODE REVIEW

**Comment by Jade-JadeH** [comment]
Copying my comments from another PR to here: 

While testing I do notice a UX improvement which is that when users enter incomplete address there's no feedback. Although I think this can be a different PR. 

Still trying to figure out when this happens because when I enter "1919 McIntyre Street" it doesn't take me anywhere, which I guess is because of incomplete address? Because "1919 McIntyre Street, Ann Arbor" does return a place.

but when I enter "380 new york street" which is also incomplete, it does take me to somewhere 

image

Maybe this is just because of the issue with REST API?

It would still be useful if on the instruction banner below we can show a message when this happens. 

image

**Comment by arash-sh** [comment]
> is just because of the issue with REST API?
> 
> It would still be useful if on the instruction banner below we can show a message when this happens.
Yes it is because that address doesn't return any candidates. You can check it by opening https://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?f=pjson&singleLine=1919%20McIntyre%20Street&token=<API-KEY>

I think it is useful to have a note (similar to the one for multiple candidates). I will leave it to @mmgaw113 and @ZackAllen whether that should be done in this PR.

**Review by ZackAllen — APPROVED** [review]
I consider it expected behavior. I would merge this fix as is and we can address the behavior for no address found later.

**Comment by Jade-JadeH** [comment]
> I think it is useful to have a note (similar to the one for multiple candidates). I will leave it to @mmgaw113 and @ZackAllen whether that should be done in this PR.

I created this issue https://devtopia.esri.com/runtime/normandy/issues/2997 in case we forget about these things

**Pull request merged**
