### PR TITLE
Sample Viewer User interface

### PR DESCRIPTION
**Pull request by mmgaw113**
Sample

New Sample User Interface

Summary

New User Interface for the Unreal Engine Sample viewer (individual samples have not be completed yet.)
This follows the User Interface and Animations created on [Figma](https://www.figma.com/file/HLmVNN1AYqIEgQlS7TADXb/Sample-Viewer-UX%2FUI-Improvement?type=design&node-id=0-1&mode=design)

The UI is functional. Please ensure when you test you either test in "Standalone" or "New Window" to ensure the scaling for the UI is correct and that nothing is out of place.

Clicking into the main part of the screen (not on the UI area or any buttons) will hide the mouse, clicking the middle mouse will show it and put the mouse into UI mode so the user can interact with the UI.

Tests

Windows

ArcGIS Maps SDK Version

Unreal 5.0 using SDK 1.2

### CODE REVIEW

**Comment by avr757** [comment]
Nice work!

Just nitpicky on a few things:

1. I thought it would be nicer to move the minimized corner logo a little bit up? Like the position from the 2nd pic below:

image

image

2. I would decrease the Warning icon and the Cancel icon by about 15% in terms of the size

image

3. When I launch the Sample Viewer, the notification menu was already there. Would be possible to make a delay start (like 2 sec) for the menu to look more like a sliding animation?

4. I noticed a small bug in the API Key input field. So if you put your cursor or paste API key in the inputfield, and then click anything outside the inputfield, the notification menu will flash in for a quick second.

UnrealEditor_bg1EsjXX4J

5. Should the sample list be arranged in alphabetical order?

image

6. I think it would be nice to have a selection indication on the selected sample. For example, when line of sight sample is currently selected, it would be nice to have "line of sight" text highlighted to give user some visual confirmation.

image

7. When I enter "3rd person controller" sample, no cursor is showing even if I toggle middle mouse button so I can't go back to the sample view menu. Is it mapped to a different key?

8. I noticed "Quit to Desktop" is gone. But I feel like it would be nice to include a quit function on the menu to be more consistent although ESC key is like a default command people that uses often.

**Comment by avr757** [comment]
Getting super close!

1. Could you align "Quit to Desktop" with the dropdown arrows from above?
    
image

2. It looks like the notification menu still pops up real quick when you put cursor in the API key inputfield and click the outside area (described in 4. from my last comment).

Other than those everything else looks great!

**Comment by NaumanIsGISMan** [comment]
Ok so this is going to be a pain, but for blueprint code can you include screenshots? It'll help debug potential issues and document the visual code

**Comment by mmgaw113** [comment]
> Ok so this is going to be a pain, but for blueprint code can you include screenshots? It'll help debug potential issues and document the visual code
[Blueprint screenshots.zip](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/files/11961925/Blueprint.screenshots.zip)

**Comment by avr757** [comment]
Comments based on the latest commit:

1. The api key field item is not expanded as default at the initial start of the app
    
image

2. Still having the issue of notification menu flashes in/out after trying to click outside of the API key field

UnrealEditor_DIYhmwLP3y

3. The highlighted color for "Quit to Desktop" did not work. And when I click it, the application did not quit either.
image

4. I just noticed that the warning icon and the cancel icon looks more blurry when comparing with other icons. What resolution pixel did you use for these two icons?

image

5. Have you tried deploy the sample viewer? How does it look?

**Comment by mmgaw113** [comment]
> Comments based on the latest commit:
> 
> 1. The api key field item is not expanded as default at the initial start of the app
> 
> image
> 
> 2. Still having the issue of notification menu flashes in/out after trying to click outside of the API key field
> 
> UnrealEditor_DIYhmwLP3y
> 
> 3. The highlighted color for "Quit to Desktop" did not work. And when I click it, the application did not quit either.
>    image
> 4. I just noticed that the warning icon and the cancel icon looks more blurry when comparing with other icons. What resolution pixel did you use for these two icons?
> 
> image
> 
> 5. Have you tried deploy the sample viewer? How does it look?

Just Fixed number 1 and 2. It was an easy fix and not sure how it got lost the first time I did it. Number 3 got messed up when I adjusted the position this morning. It is fixed now as well. 

The images are the native resolution and just downscaled so I'm not too sure what's up with that. I am making a build now to see how it runs.

**Review by NaumanIsGISMan — APPROVED** [review]
Overall, looks good, nice work. One thing I would change before merging is that I noticed that the main menu, when you select a scene, slides down and to the left at an angle instead of moving perfectly horizontally

**Pull request merged**
