### PR TITLE
Mas12517/user interface/feature layer and Line of Sight UI

### PR DESCRIPTION
**Pull request by mmgaw113**
**Sample**

- Line of Sight sample
- Feature Layer Sample

**Summary**

- Updates to User Interface for Line of Sight sample
- Updates to User Interface for Feature Layer Sample
- Fix Feature Layer sample, stadiums spawning at world origin

**Tests**

Windows

**ArcGIS Maps SDK Version**

UE 5.0 w/Maps SDK v1.2

### CODE REVIEW

**Comment by avr757** [comment]
I had BP compile errors
image

and it kept crashing after I attempted to go into feature layer

```
LoginId:1ae053534284f3987cb1689a568a6475
EpicAccountId:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000050

UnrealEditor_sample_project!AFeatureLayer::OnResponseRecieved() [C:\Users\and12279\Documents\GitHub\arcgis-maps-sdk-unreal-engine-samples\sample_project\Source\sample_project\Feature Layer\FeatureLayer.cpp:43]
UnrealEditor_sample_project!TBaseUObjectMethodDelegateInstance<0,AFeatureLayer,void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:609]
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Comment by mmgaw113** [comment]
Make sure you build the solution file. I made some major changes to the Feature Layer c++ file and that will happen if you don't build first

**Review by avr757 — CHANGES_REQUESTED** [review]
The feature layer is looking real nice! Great work.

A couple of things to keep in mind,

1) the instruction menu is lacking some consistency in terms of the font size. The one from the Line of Sight is looking significantly smaller. If you look at the 3rd pic down below when I compare the two designs from Figma, you see that both instruction menus are consistent in terms of font size and alignment. So please use a lay over as a reference to get the alignment right and double check before making a commit. I think it would be easier if you use a prefab equivalent for unreal to save the barebone menu or template to ensure consistency.

image

image

image

2) Again, the line of sight instruction and font is a little too small, more importantly, Navigate, Rotate View, Pan View text are too close to the icons above. 2nd pic down below is the Figma design. You gotta pay close attention to these margins.

image

Instruction-Line of Sight (1)

3) The drop down design is looking good. But personally I thought the animation is lil strange with the partial fading and sliding. I think it will look more legit if you just do no sliding/no fading to make the drop-down just appear straight up.

UnrealEditor_mIxexnPY1a

4) For the Info Icon, instead of fading the icon color to dark grey when doing mouse hover, can you just fade the purple background instead?

UnrealEditor_hyoYcPQucw

Like this: 
Unity_tyC9uRZ7YI

**Comment by avr757** [comment]
Line of sight is looking good now, for the feature layer, can you line up the instructions menu vertically with the info icon?

image

Also, are you planning to implement the stadium name shown as below? or that's gonna be part of future work?

image

**Comment by mmgaw113** [comment]
I tried to get the name for each stadium but unfortunately it is a lot more complicated. Additionally it might be worth talking about whether we still want to do that if we are planning to redo the sample in the near future.

**Review by avr757 — APPROVED** [review]
looking great!

**Pull request merged**
