### PR TITLE
Jad10309 api warning

### PR DESCRIPTION
**Pull request by Jade-JadeH**
This PR fixes the following API UX issues: 

1. The samples are still clickable even when there's no API key. 
2. The API warning is not reacting to API changes in runtime, for example, if there's no API key in the beginning and user enter one, the warning doesn't go away; similarly, if there's API key and user removes it, the warning doesn't appear. In general, our notification should always respond to user action in runtime instead of a static notification. 

Overall, this PR does the following
- [x] sample list greys out and deactivates when there's no API key on both project settings or sample viewer scene, or if users delete the API key
- [x] Change the banner to warning signs per UI design, warning sign appears when there's no API key on both project settings or sample viewer scene, or if users delete the API key
- [x] warning sign disappears when there's API key on either project settings or sample viewer scene, or if users enter the API key
- [x] tooltip shows on hover

### CODE REVIEW

**Comment by mmgaw113** [comment]
image
image
Can't test in UE 5.0 since this PR was done in 5.1

**Comment by Jade-JadeH** [comment]
> image image Can't test in UE 5.0 since this PR was done in 5.1

which version did you test with?

**Comment by avr757** [comment]
Unreal 5.0 worked on my end so far. I haven't tested with 5.1 though.

UnrealEditor_1ZixYBaupi

**Comment by mmgaw113** [comment]
> Unreal 5.0 worked on my end so far. I haven't tested with 5.1 though.
> 
> UnrealEditor_1ZixYBaupi [ UnrealEditor_1ZixYBaupi ](https://private-user-images.githubusercontent.com/106696949/291999049-d0fa58be-d068-4853-a1f2-778b95fa3f75.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDE0OTksIm5iZiI6MTcwMzEwMTE5OSwicGF0aCI6Ii8xMDY2OTY5NDkvMjkxOTk5MDQ5LWQwZmE1OGJlLWQwNjgtNDg1My1hMWYyLTc3OGI5NWZhM2Y3NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxOTM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJmMWQ2ZTdmMjllY2MxYzc4NmQzNDhmYjM0N2RkZWQ3ZThkMWQyMzhiODk1NmE2YWI5NzU3NjMzZTY0YWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBY-2JIIIsYw57f7_s70tVK_ouW-pwiHjd4pe0yjOBU) [ ](https://private-user-images.githubusercontent.com/106696949/291999049-d0fa58be-d068-4853-a1f2-778b95fa3f75.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDE0OTksIm5iZiI6MTcwMzEwMTE5OSwicGF0aCI6Ii8xMDY2OTY5NDkvMjkxOTk5MDQ5LWQwZmE1OGJlLWQwNjgtNDg1My1hMWYyLTc3OGI5NWZhM2Y3NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxOTM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJmMWQ2ZTdmMjllY2MxYzc4NmQzNDhmYjM0N2RkZWQ3ZThkMWQyMzhiODk1NmE2YWI5NzU3NjMzZTY0YWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBY-2JIIIsYw57f7_s70tVK_ouW-pwiHjd4pe0yjOBU)

Are you sure you are testing in 5.0? I get this warning when i open the project 
image

**Review by mmgaw113 — CHANGES_REQUESTED** [review]
It does not work in 5.1 and likely other newer versions. Please take a look at how I did it on the branch I sent you and make changes accordingly. I think you might be over complicating this a little bit...

**Comment by Jade-JadeH** [comment]
> It does not work in 5.1 and likely other newer versions. Please take a look at how I did it on the branch I sent you and make changes accordingly. I think you might be over complicating this a little bit...

I checked your branch. It appears that you're using a event tick which is expensive. Mine only check API key on event construct and when user starts typing because that's the only two times the API key might get changed. Whenever possible we should avoid using event tick. 

A couple of other issues include that your warning message doesn't reappear when user starts deleting character from the original API key. The point of my PR is to make the warning message reacts to user typing in runtime. That's why I have extra steps in my PR, 

As for make the warning message appear and disappear it appears you also use the set visibility node so it's the same approach as I used

**Comment by mmgaw113** [comment]
Yeah, I did it on tick but that branch was for showing that it works and wasn’t intended to be merged into main unless we couldn’t find the issue. 

The issue you are running into is that you are attempting to set the image variable that is on the canvas which is not allowed. You shouldn’t even need to set the image variable with the exception of in the canvas. After that changing the visibility should be enough to solve the issue.

**Comment by mmgaw113** [comment]
A couple things I noticed when testing:
1.) If you put an API Key into the Make Literal Text Node in the Sample BP Game Mode the following happens (see images)
image
image


2.) If you put an API Key into the API Key Variable in the Sample BP Game Mode, it won't recognize the api key is in there at all. 
image
image

**Comment by Jade-JadeH** [comment]
@mmgaw113 

1. this one is fixed now, good catch!
2. This issue is present in the original bp too, it only checks project settings and `literal text` node. I added another `select `node so that it now recognizes the API key variable.

**Review by mmgaw113 — APPROVED** [review]

**Pull request merged**
